### ISSUE TITLE
`git status` check as a build step

### ISSUE THREAD

**Issue by mrdavidburns** [Lullabot/drainpipe#396] opened 2024-02-05 18:14 UTC
In most cases we would want no file differences before and after a pull request builds a project. Running `git status` should show any files that do not match changes committed to  the repository. 

1. Do we block the PR from being merged? 
  - It may be intentional that we're not committing all changes from `composer install`. For example Drainpipe may have customized changes inside the `.tugboat/scripts` which a developer doesn't want to commit to the project.

**Comment by justafish** [comment] 2024-02-15 13:25
Duplicate of #247

**Closed by justafish** 2024-02-15 13:25 UTC

**Comment by deviantintegral** [comment] 2024-02-19 14:51
The issue is #225 .
