### ISSUE TITLE
Add composer-lock-diff configuration to post in comment always, comment for renovate PRs, description always

### ISSUE THREAD

**Issue by beto-aveiga** [Lullabot/drainpipe#239] opened 2023-08-02 22:54 UTC
When using Renovate Bot and Drainpipe with Composer lock diff, the PR description gets overwritten by Drainpipe, removing our composer lock diff information.

### Feature request
It would be great to have 2 things:
- A setting to inform drainpipe when a PR is created/managed by Renovate Bot, to not write the composer-lock-diff information into the PR description
- Write the composer-lock-diff info into a PR review.

### Working code

The following code is a modification from Drainpipe's composer lock diff workflow, and it writes the composer-lock-diff result to a PR review.

`.github/workflows/ComposerLockDiff-renovate.yml`

You may have better ways to integrate it with Drainpipe.
 
```
name: "Composer Lock Diff for Renovate PRs"

on:
  pull_request:
    branches:
      - 'renovate/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  Composer-Lock-Diff:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.ref }}

      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.ddev/.drainpipe-composer-cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - uses: ./.github/actions/drainpipe/set-env

      - name: Install and Start DDEV
        uses: ./.github/actions/drainpipe/ddev
        with:
          git-name: Drainpipe Bot
          git-email: no-reply@example.com
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Build Project
        run: ddev composer install

      - name: Install composer lock diff
        run: ddev composer global require davidrjonas/composer-lock-diff:^1.0

      - name: Get the ID of the last review (if any)
        run: |

          response=$(curl --location \
            --header "Accept: application/vnd.github+json" \
            --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            --header "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/pulls/$DRAINPIPE_PR_NUMBER/reviews)

          # LAST_REVIEW_ID won't be empty when we already have a review.
          # If so, we will update the review later, instead of creating one.
          github_action_reviews=$(echo "$response" | jq '.[] | select(.user.login == "github-actions[bot]")')
          echo "LAST_REVIEW_ID=$(echo "$github_action_reviews" | jq --raw-output '.id' | tail --lines 1)" >> $GITHUB_ENV

      - name: Run composer lock diff
        run: |

          vendor/bin/composer-lock-diff \
            --from=origin/${{ github.event.pull_request.base.ref }}:composer.lock \
            --to=HEAD:composer.lock --md > composer-lock-diff.txt

          if [ $(wc --bytes < composer-lock-diff.txt) -lt 1 ]; then
              echo -e "No package differences found." > composer-lock-diff.txt
          fi

          # Generating the title with new line.
          echo '## Composer Lock Diff' > composer-lock-diff-title.txt
          echo " " >> composer-lock-diff-title.txt

          # Appending the title.
          json_body_value=$(cat composer-lock-diff-title.txt)$(cat composer-lock-diff.txt)

          # Create a JSON object with the contents in the "body" key.
          composer_lock_diff_json=$(jq --null-input --arg body "$json_body_value" '{"body": $body}')

          # New reviews must contain event:"COMMENT", otherwise the review state
          # will be "pending".
          if [ -z "$LAST_REVIEW_ID" ]; then
            composer_lock_diff_json=$(jq --null-input --arg body "$json_body_value" --arg event "COMMENT" '{"body": $body, "event": $event}')
          else
            composer_lock_diff_json=$(jq --null-input --arg body "$json_body_value" '{"body": $body}')
          fi

          # Store the JSON object back into the file.
          echo "$composer_lock_diff_json" > composer-lock-diff.json

      - name: Edit last review (if any)
        if: env.LAST_REVIEW_ID != ''
        run: |

          curl --location \
            --request PUT \
            --header "Accept: application/vnd.github+json" \
            --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            --header "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/pulls/$DRAINPIPE_PR_NUMBER/reviews/$LAST_REVIEW_ID \
            --data @composer-lock-diff.json

      - name: Create a Review
        if: env.LAST_REVIEW_ID == ''
        run: |

          curl --location \
            --request POST \
            --header "Accept: application/vnd.github+json" \
            --header "X-GitHub-Api-Version: 2022-11-28" \
            --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            https://api.github.com/repos/${{ github.repository }}/pulls/$DRAINPIPE_PR_NUMBER/reviews \
            --data @composer-lock-diff.json

```

**Comment by davereid** [comment] 2024-01-08 16:13
Related: https://github.com/Lullabot/drainpipe/issues/317

**Comment by davereid** [comment] 2024-02-01 15:58
I will look into removing DDEV and just using native composer with https://github.com/Lullabot/drainpipe/issues/332 which would solve this issue. I'm out on vacation for the next 7 days so if you feel like you can move this part forward, feel free to do so! Otherwise this is one of my top priorities when I get back.

**Comment by deviantintegral** [comment] 2024-02-01 18:43
> I will look into removing DDEV and just using native composer with https://github.com/Lullabot/drainpipe/issues/332 which would solve this issue

Mind sharing how? Re-reading the description I wonder if this is basically a duplicate of https://github.com/Lullabot/drainpipe/issues/332.

**Comment by davereid** [comment] 2024-02-01 18:51
Yeah, I think this could likely be closed as a duplicate of https://github.com/Lullabot/drainpipe/issues/332 that accomplishes both things.

**Closed** 2024-02-19 20:09 UTC
